### ISSUE TITLE
Ensure current connection info remains available during ZDT

### ISSUE THREAD

**Issue by enocom** [GoogleCloudPlatform/cloud-sql-nodejs-connector#220]
During Zonal Down Time, the Connector will experience a short period of connection failures. Currently, we force refresh on each connection failure. This feature request is to ensure that if the refresh is rate limited, the current connection info remains available to support fast re-connections.

**Comment by enocom** [comment]
This is probably just a matter of deleting these lines:

https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector/blob/main/src/cloud-sql-instance.ts#L101-L104

**Comment by ruyadorno** [comment]
I believe this was handled in https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector/pull/219, more specifically this line should take care of refreshing automatically and still apply rate limits on connection failures:

https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector/blob/290d741b00545bb801431d8711b1de4285da17d0/src/cloud-sql-instance.ts#L161

While current connection info should also remain available to support new connections, given that we only update values in a `CloudSQLInstance` once a refresh has successfully completed:

https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector/blob/290d741b00545bb801431d8711b1de4285da17d0/src/cloud-sql-instance.ts#L141-L143

@jackwotherspoon I know you helped me review some of this logic and I would love to have your input here. Should we close this issue?

**Comment by enocom** [comment]
What I'm wondering about is the significance of this line:

https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector/blob/290d741b00545bb801431d8711b1de4285da17d0/src/cloud-sql-instance.ts#L111

**Comment by ruyadorno** [comment]
oh, this never really blocks anything (other than in tests) since the only place `forceRefresh` is called from is this callback handler that doesn't block any other logic:

https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector/blob/290d741b00545bb801431d8711b1de4285da17d0/src/connector.ts#L220-L222

Connection attempts from the driver would not be prevented from that. Looking at this particularly part of the code, I believe I should remove the `async/await` since it server no purpose here in this callback.

**Comment by enocom** [comment]
Got it. In that case, I agree -- we fixed this in #219.

**Comment by ruyadorno** [comment]
Sounds good 👍 thanks @enocom!
